# Time Series Analysis and Visualization Using Python and Plotly

## Task 1: Import the libraries

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import pycountry_convert as pc
import io
import PIL

## Task 2: Read in Data

In [2]:
gdp = pd.read_csv('gdp_pcap.csv')
lex = pd.read_csv('life_expectancy.csv')
pop = pd.read_csv('population.csv')

## Task 3: Perform Visual and Programmatic Assessment

In [3]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Columns: 302 entries, country to 2100
dtypes: int64(92), object(210)
memory usage: 460.2+ KB

In [4]:
gdp.describe()

,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,...,1882,1883,1884,1885,1886,1888,1890,1893,1894,1895
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,...,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000
mean,1250.589744,1249.800000,1253.569231,1252.682051,1254.902564,1254.728205,1256.200000,1256.446154,1244.902564,1246.646154,...,1955.738462,1978.866667,1995.584615,2008.282051,2022.235897,2077.697436,2098.723077,2146.297436,2187.169231,2204.548718
std,696.566865,693.356594,708.047067,700.758758,711.654581,703.361519,705.617574,697.620869,645.755392,652.828645,...,1539.933838,1585.361818,1595.250798,1608.352697,1621.265757,1672.043899,1700.882256,1694.756603,1722.451174,1763.645595
min,430.000000,430.000000,430.000000,430.000000,430.000000,430.000000,430.000000,430.000000,430.000000,430.000000,...,494.000000,498.000000,502.000000,506.000000,510.000000,518.000000,527.000000,538.000000,538.000000,538.000000
25%,770.500000,771.500000,772.000000,772.000000,772.500000,773.000000,774.000000,774.500000,775.500000,776.000000,...,969.000000,973.500000,978.500000,992.500000,986.500000,1015.000000,1010.000000,1025.000000,1035.000000,1020.000000
50%,1120.000000,1120.000000,1120.000000,1120.000000,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000,1130.000000,...,1440.000000,1450.000000,1460.000000,1470.000000,1480.000000,1500.000000,1500.000000,1550.000000,1600.000000,1570.000000
75%,1485.000000,1480.000000,1475.000000,1475.000000,1470.000000,1470.000000,1465.000000,1475.000000,1465.000000,1465.000000,...,2350.000000,2385.000000,2405.000000,2435.000000,2470.000000,2525.000000,2555.000000,2615.000000,2685.000000,2700.000000
max,5810.000000,5700.000000,6020.000000,5890.000000,6170.000000,5810.000000,5850.000000,5360.000000,4510.000000,4590.000000,...,9100.000000,9900.000000,9520.000000,9780.000000,9580.000000,9960.000000,9860.000000,9480.000000,9510.000000,9940.000000

In [5]:
print(gdp.value_counts())
print(gdp.isnull())
print(gdp.duplicated())

country      1800  1801  1802  1803  1804  1805  1806  1807  1808  1809  1810  1811  1812  1813  1814  1815  1816  1817  1818  1819  1820  1821  1822  1823  1824  1825  1826  1827  1828  1829  1830  1831  1832  1833  1834  1835  1836  1837  1838  1839  1840  1841  1842  1843  1844  1845  1846  1847  1848  1849  1850  1851  1852  1853  1854  1855  1856  1857  1858  1859  1860  1861  1862  1863  1864  1865  1866  1867  1868  1869  1870  1871  1872  1873  1874  1875  1876  1877  1878  1879  1880  1881  1882  1883  1884  1885  1886  1887  1888  1889  1890  1891  1892  1893  1894  1895  1896  1897  1898  1899  1900  1901  1902  1903  1904  1905  1906  1907  1908  1909  1910  1911  1912  1913  1914  1915  1916  1917  1918  1919  1920  1921  1922  1923  1924  1925  1926  1927  1928  1929  1930  1931  1932  1933  1934  1935  1936  1937  1938  1939  1940  1941  1942  1943  1944  1945  1946  1947  1948   1949   1950   1951   1952   1953   1954   1955   1956   1957   1958   1959   1960   1961   1962   1963   1964   1965   1966   1967   1968   1969   1970   1971   1972   1973   1974   1975   1976   1977  1978   1979   1980   1981   1982   1983   1984   1985   1986   1987   1988   1989   1990   1991   1992   1993   1994   1995   1996   1997   1998   1999   2000   2001   2002   2003   2004   2005   2006   2007   2008   2009   2010   2011   2012   2013   2014   2015   2016   2017   2018   2019   2020   2021   2022   2023   2024   2025   2026   2027   2028   2029   2030   2031   2032   2033   2034   2035   2036   2037   2038   2039   2040   2041   2042   2043   2044   2045   2046   2047   2048   2049   2050   2051   2052   2053   2054   2055   2056   2057   2058   2059   2060   2061   2062   2063   2064   2065   2066   2067   2068   2069   2070   2071   2072   2073   2074   2075   2076   2077   2078   2079   2080   2081   2082   2083   2084   2085   2086   2087   2088   2089   2090   2091   2092   2093   2094   2095   2096   2097   2098   2099   2100
Afghanistan  583   583   583   583   583   583   583   583   583   583   583   583   583   583   583   583   583   583   583   583   583   583   584   586   587   588   590   591   592   594   595   596   598   599   600   602   603   604   606   607   609   610   611   613   614   615   617   618   620   621   622   624   625   627   628   630   631   632   634   635   637   638   640   641   642   644   645   647   648   650   651   653   654   656   657   659   660   662   663   665   666   666   675   683   692   700   709   718   727   737   746   755   765   775   784   794   804   814   825   835   846   856   867   878   889   900   912   923   935   947   959   971   983   996   1010  1020  1030  1050  1060  1070  1090  1100  1110  1130  1140  1160  1170  1190  1200  1220  1230  1250  1260  1280  1300  1310  1330  1350  1360  1380  1400  1420  1440  1460  1480  1500  1530  1550  1570   1590   1620   1660   1690   1770   1780   1780   1830   1800   1870   1890   1920   1900   1890   1890   1880   1890   1860   1880   1900   1880   1880   1830   1490   1500   1550   1600   1650   1530  1610   1540   1540   1730   1920   2050   2030   1990   2050   1850   1690   1540   1480   1360   1310   897    666    986    937    892    854    815    791    772    1260   1280   1260   1350   1370   1540   1560   1830   2030   1960   2120   2170   2140   2110   2100   2100   2060   2080   1970   1520   1430   1400   1370   1370   1380   1400   1420   1460   1480   1530   1500   1550   1580   1610   1640   1640   1670   1710   1700   1730   1560   1610   1500   1580   1930   2060   2150   2290   2390   2280   2100   2160   2280   2390   2510   2540   2700   2280   2200   2050   2070   1880   1960   1940   2050   2420   2360   2530   2640   2630   2690   2810   2650   2690   2800   2920   2990   3110   2990   2740   2830   2930   3020   3090   3200   3280   3360   3450   3550   3570   3700   3720   3830   3930   4030   4130   3900   4070   4030     1
Albania      569   571   572   574   576   577   579   581   582   584   586   587   589   591   592   594   596   597   599   601   603   604   606   608   610   611   613   615   617   618   620   622   624   625   627   629   631   633   634   636   638   640   642   644   646   647   649   651   653   655   657   659   660   662   664   666   668   670   672   674   676   678   680   682   684   685   687   689   691   693   695   697   699   701   703   705   707   709   711   714   716   718   720   722   724   726   728   730   732   734   736   738   741   743   745   747   749   751   753   756   758   760   762   764   766   769   771   773   775   777   780   782   784   787   810   834   859   884   911   938   966   994   1020  1050  1090  1120  1150  1190  1220  1260  1290  1330  1370  1410  1460  1500  1540  1590  1640  1690  1740  1790  1840  1900  1950  2010  2070  2130  2200   2260   2330   2310   2320   2410   2480   2620   2640   2810   2940   3060   3220   3240   3350   3460   3580   3710   3850   4000   4150   4290   4450   4580   4700   4860   4910   4950   5010   5060  5120   5190   5230   5360   5400   5380   5390   5280   5410   5320   5210   5470   5020   3650   3430   3770   4090   4600   5020   4490   4910   5580   6000   6550   6870   7270   7690   8140   8660   9220   9960   10.3k  10.8k  11.1k  11.2k  11.4k  11.6k  11.9k  12.3k  12.8k  13.3k  13.7k  13.3k  14.5k  15.1k  15.6k  16.1k  16.7k  17.3k  17.9k  18.5k  19.2k  18.7k  19.4k  19.7k  20.2k  20.7k  20.8k  21.2k  21.8k  21k    20.4k  21k    22.1k  23.2k  24.3k  24.1k  24.9k  25.4k  26.2k  27k    27.8k  28.6k  29k    29k    27.6k  27.9k  27.8k  27.3k  27.7k  28.9k  28.9k  28k    28.6k  28.6k  29.3k  29.1k  30.2k  31.3k  32.3k  33.2k  34.1k  29.9k  29.5k  29.1k  30.3k  31.4k  32.7k  33.3k  34.6k  34k    35.1k  31.8k  31k    31.9k  32.8k  33.7k  34.7k  35.6k  36.6k  37.5k  38.1k  38.1k  37.6k  38.5k  39.4k  39.9k  40.9k  41.9k  41.4k  42.4k  43.7k  45.7k    1
Algeria      925   926   927   929   930   931   933   934   935   936   938   939   940   942   943   944   946   947   948   949   951   960   970   980   990   1000  1010  1020  1030  1040  1050  1060  1070  1090  1100  1110  1120  1130  1140  1150  1170  1180  1190  1200  1210  1230  1240  1250  1260  1280  1290  1300  1320  1330  1340  1360  1370  1390  1400  1410  1430  1440  1460  1470  1490  1500  1520  1530  1550  1570  1580  1600  1620  1640  1660  1670  1690  1710  1730  1750  1770  1790  1810  1830  1850  1870  1900  1920  1940  1960  1980  2010  2030  2050  2080  2100  2120  2150  2170  2200  2220  2250  2270  2300  2320  2350  2380  2400  2430  2460  2490  2520  2540  2570  2580  2600  2610  2620  2630  2640  2650  2660  2680  2690  2700  2710  2720  2730  2750  2760  2770  2780  2790  2810  2820  2830  2840  2850  2870  2880  2890  2920  2950  2980  3010  3030  3060  3090  3120   3150   3180   3160   3240   3240   3420   3460   3740   4100   4180   4880   5130   4600   3430   4240   4420   4640   4270   4580   4970   5290   5680   5050   5990   6070   6220   6450   6700   7130  7740   8160   8040   8040   8320   8520   8740   8880   8630   8380   8010   8190   8100   7930   7990   7740   7600   7820   8070   8090   8430   8630   8880   9060   9460   10k    10.3k  10.8k  10.8k  10.9k  11k    10.9k  11k    11.1k  11.3k  11.4k  11.6k  11.8k  11.9k  11.8k  11.7k  11.6k  10.8k  11k    11.4k  11.5k  11.6k  11.7k  11.7k  11.8k  12k    12.2k  12k    12.2k  12.6k  13.1k  13.2k  13.7k  14.2k  14.8k  15.4k  16.1k  16.4k  17k    17.5k  16.3k  16.7k  16.3k  16.5k  16.8k  17.2k  17.3k  17.8k  18.1k  18.4k  18.6k  18.8k  18.6k  18.8k  19.3k  19.7k  20.2k  18.9k  19.4k  19.8k  20.3k  20.5k  20.9k  21.4k  21.8k  22.3k  22.8k  23k    22.7k  22.5k  23.1k  23.6k  24.2k  24.7k  25.3k  25.8k  25.8k  25.1k  25.3k  25.8k  26.3k  26.8k  29.5k  30k    30.5k  30.6k  31.2k  31.9k  32.8k  33.1k  33.5k  34k    35.1k  35.4k  36.6k  37k    38.2k  38.2k    1
Andorra      1660  1660  1670  1670  1670  1680  1680  1680  1690  1690  1690  1690  1700  1700  1700  1710  1710  1710  1720  1720  1720  1740  1760  1780  1810  1830  1850  1870  1890  1920  1940  1960  1990  2010  2030  2060  2080  2110  2130  2160  2180  2210  2230  2260  2290  2310  2340  2370  2400  2430  2460  2490  2510  2550  2570  2600  2640  2670  2700  2730  2760  2800  2830  2860  2900  2930  2970  3000  3040  3070  3110  3150  3190  3220  3260  3300  3340  3380  3420  3460  3500  3540  3580  3630  3670  3710  3760  3800  3850  3890  3940  3990  4030  4080  4130  4180  4230  4280  4330  4380  4430  4490  4540  4590  4650  4700  4760  4820  4870  4930  4990  5050  5110  5170  5260  5350  5430  5530  5620  5710  5810  5910  6010  6120  6220  6330  6440  6550  6660  6780  6890  7010  7130  7260  7380  7510  7640  7770  7900  8040  8180  8330  8490  8650  8810  8970  9140  9310  9490   9670   9850   10.7k  11.5k  12.5k  13.5k  14.7k  15.9k  17.2k  18.6k  20.2k  21.8k  23.6k  25.6k  27.7k  30k    32.5k  35.2k  38.1k  41.2k  44.7k  48.3k  48.2k  49.6k  51k    51.7k  50k    50k    50k   49.4k  47.9k  47.4k  45.6k  44.4k  43.3k  42.3k  41.5k  41.1k  41.8k  42.3k  42.7k  42.7k  42.2k  41k    39.3k  39.2k  39.6k  41.2k  45.2k  46.9k  48.7k  48.3k  48.6k  48.8k  52.9k  55.8k  61.2k  65.9k  67.1k  64.1k  64.6k  60.5k  60.9k  57.9k  55.7k  56.6k  56.5k  57.5k  56.4k  56.2k  56.3k  49.7k  53.1k  55.6k  55.6k  55.8k  55.9k  55.8k  55.6k  55.5k  55.5k  53.2k  53.5k  54.3k  55.2k  54.8k  55.3k  55k    55.9k  56.7k  57.4k  57.9k  58.4k  58.8k  59.3k  59.7k  60.1k  58k    59.2k  59.7k  60.9k  63.3k  61.6k  61.7k  61.5k  61.7k  62.7k  63.3k  64.5k  65.8k  64k    56.9k  58.2k  58.9k  59.4k  59k    59.5k  60.1k  59.7k  60.5k  61.3k  59.9k  57.3k  56.4k  57k    57.7k  58.3k  58.7k  59.2k  59.6k  60.1k  53.7k  54.2k  55.4k  57.3k  55.1k  54.3k  56.1k  57.1k  57.5k  58.1k  58.6k  59.2k  60k    60.3k  61k    61.7k  62.7k  61.9k  62.5k  62.9k  62.1k    1
Angola       452   454   456   458   460   462   464   466   468   470   472   474   476   479   481   483   485   487   489   491   493   495   498   500   502   504   506   509   511   513   515   518   520   523   525   527   529   531   534   537   539   541   544   546   548   550   553   556   558   561   563   566   568   570   573   575   578   580   583   586   588   591   594   596   599   602   604   607   609   612   615   618   620   623   626   628   631   634   637   640   643   645   648   651   654   656   659   662   665   668   671   674   677   680   683   686   689   692   695   698   701   704   708   711   714   717   720   723   726   730   733   736   739   742   765   787   811   835   859   885   911   941   971   1000  1030  1070  1100  1140  1170  1210  1250  1290  1330  1370  1410  1460  1500  1550  1600  1650  1700  1780  1860  1940  2030  2120  2210  2310  2410   2520   2630   2730   2830   2930   2840   3060   2990   3270   3430   3430   3550   4010   3880   4060   4500   4810   5070   5340   5230   5360   5670   5750   5720   6040   5950   4570   4200   4190  4110   4110   4160   3990   3880   3890   4000   3850   3760   3990   4310   4310   4210   4250   3990   3020   3040   3470   3900   4140   4270   4310   4370   4480   4990   5030   5440   6100   6630   7340   7870   7640   7690   7660   8010   8100   8180   7970   7490   7220   6880   6600   6030   5910   5900   5930   5980   6040   6100   6180   6290   6430   6300   6440   6540   6570   6480   6590   6790   7000   7180   7440   7440   7720   7490   7760   8040   8390   9260   9570   9940   10.3k  10.4k  10.2k  10.1k  10.1k  10.1k  10.3k  10.4k  10.7k  11.1k  11k    10.7k  10.9k  11.1k  11.4k  11.7k  12.1k  12.5k  12.9k  13.3k  13.6k  13.6k  13.4k  13.3k  13.7k  14.1k  14.6k  14.9k  15.2k  15.7k  16k    15.4k  15.8k  16.2k  16.7k  16.9k  17.4k  18k    18.6k  19.2k  19.3k  20k    20.6k  21.1k  21.7k  21.9k  22.3k  22.5k  23k    23.5k  24k    24.6k    1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ..
Venezuela    1490  1480  1470  1470  1460  1450  1440  1440  1430  1420  1410  1410  1400  1390  1390  1380  1370  1360  1360  1350  1340  1440  1540  1650  1770  1890  2030  2170  2330  2490  2670  2630  2970  3020  3050  2990  2780  2610  2350  2190  2110  2350  2610  2430  2430  2460  2480  2380  2380  2190  2610  2510  2610  2780  2830  2940  2270  2610  2560  2590  2750  2960  2610  2400  2350  2480  2460  2210  2240  2480  2460  2400  2430  2610  2880  2560  2670  2700  2880  2830  2990  2990  2940  3070  3260  3020  3200  3310  3310  3440  3710  3500  3150  3150  3100  3360  2960  3040  2960  2510  2560  2460  2300  2460  2480  2510  2480  2400  2350  2350  2320  2210  2380  2430  2800  2800  2610  2720  2830  2720  2640  2560  2780  2910  3020  3180  3360  3420  3980  4080  4060  4030  3660  4060  4220  5020  5420  5390  5950  6300  6620  6420  5540  6110  6580  8000  9160  8930  10.6k  10.7k  11.6k  12.3k  12.8k  13k    13.7k  14.3k  15.1k  16.1k  15.7k  16.1k  15.7k  15.8k  16.6k  17k    18.1k  18.4k  17.9k  18k    18.5k  18.7k  19.8k  19.7k  19.6k  20.1k  20.7k  21.2k  22.3k  23k   22.8k  22.3k  21.2k  20.4k  20.1k  18k    17.9k  17.5k  18.3k  18.6k  19.2k  16.4k  17k    18.2k  18.8k  18.5k  17.6k  17.9k  17.5k  18.2k  17.9k  16.5k  16.5k  16.8k  15k    13.6k  15.8k  17.1k  18.4k  19.7k  20.3k  19.3k  18.7k  19.2k  20k    20k    18.9k  17.5k  14.5k  12.3k  10.4k  7840   5460   5560   5500   5500   5530   5580   5630   5690   5780   5870   5880   6020   6100   6240   6400   6490   6660   6850   6970   7150   7340   7510   7690   7880   8060   8250   8450   8640   8760   8990   9150   9120   9270   9170   9170   9210   9340   9590   9830   10.1k  9380   9580   9720   9310   9710   10.1k  10.5k  10.8k  11.3k  11.6k  11.7k  11.7k  11.7k  12k    12.3k  12.6k  12.9k  13.2k  13.6k  14k    13.2k  13.5k  13.9k  14.3k  14.6k  15.1k  15.3k  15.8k  16.2k  16.6k  16.9k  17.4k  17.2k  17.8k  18.4k  19.1k  19.5k  19.8k  20.3k  20.8k  21.3k    1
Vietnam      1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1170  1160  1160  1160  1160  1160  1160  1160  1160  1160  1160  1150  1150  1150  1150  1150  1150  1150  1150  1150  1150  1150  1140  1140  1140  1140  1140  1140  1140  1140  1140  1140  1130  1130  1130  1130  1130  1130  1130  1130  1130  1130  1120  1120  1120  1120  1120  1120  1120  1120  1120  1130  1140  1150  1160  1170  1180  1190  1200  1210  1220  1230  1240  1250  1260  1270  1280  1290  1300  1310  1320  1330  1350  1360  1370  1380  1390  1400  1420  1430  1440  1450  1470  1480  1490  1500  1520  1530  1540  1550  1570  1580  1590  1610  1600  1600  1600  1590  1590  1580  1580  1570  1570  1570  1560  1560  1550  1550  1540  1540  1540  1530  1530  1520  1520  1520  1510  1510  1500  1500  1500  1490  1480  1470  1460  1450  1440  1430  1420   1410   1410   1440   1470   1500   1540   1570   1600   1610   1630   1640   1650   1670   1810   1800   1820   1780   1730   1470   1400   1480   1460   1490   1530   1530   1470   1400   1550   1640  1620   1650   1560   1600   1690   1760   1870   1940   1960   1970   2030   2120   2150   2220   2360   2500   2660   2860   3080   3270   3410   3520   3710   3900   4100   4340   4610   4910   5190   5510   5760   6010   6320   6660   6950   7260   7640   8090   8550   9050   9640   10.3k  10.5k  10.6k  11.3k  11.9k  12.5k  13.3k  14k    14.9k  15.7k  16.6k  16.6k  16.9k  17.3k  17.8k  18k    18.4k  18.9k  19.4k  19.9k  20.4k  20.9k  21.4k  21.7k  22.1k  22.7k  23.2k  23.1k  23.7k  24.2k  24.8k  25.3k  25.9k  25.7k  25.8k  26.3k  26.7k  26.6k  27.1k  27.7k  27.9k  27.6k  28.2k  28.9k  29.5k  30.1k  30.8k  31.5k  32.2k  32.4k  33.1k  33.4k  33.4k  33.4k  34.3k  35.2k  35.9k  36.6k  37.3k  38k    38.2k  36.3k  36.9k  37.6k  38.3k  39k    39.4k  40.1k  40.7k  41.4k  41.9k  42.7k  43.1k  43.7k  44.4k  45.1k  45.8k  46.6k  46.8k  47.2k  48.3k  48.9k    1
Yemen        1220  1230  1230  1230  1240  1240  1240  1250  1250  1250  1260  1260  1270  1270  1270  1280  1280  1280  1290  1290  1300  1300  1300  1310  1310  1310  1320  1320  1320  1330  1330  1340  1340  1340  1350  1350  1360  1360  1360  1370  1370  1370  1380  1380  1390  1390  1390  1400  1400  1410  1410  1410  1420  1420  1430  1430  1430  1440  1440  1450  1450  1450  1460  1460  1470  1470  1480  1480  1480  1490  1490  1500  1500  1500  1510  1510  1520  1520  1530  1530  1540  1540  1540  1550  1550  1560  1560  1570  1570  1570  1580  1580  1590  1590  1600  1600  1610  1610  1610  1620  1620  1630  1630  1640  1640  1650  1650  1660  1660  1670  1670  1670  1680  1680  1690  1690  1700  1700  1710  1710  1720  1720  1730  1730  1740  1740  1750  1750  1760  1760  1770  1770  1780  1780  1790  1790  1800  1800  1810  1810  1820  1820  1830  1830  1830  1840  1840  1840  1850   1850   1850   1850   1850   1840   1840   1840   1830   1820   1820   1810   1800   1800   1790   1790   1790   1790   1790   1800   1800   1800   2110   2410   2530   2750   2820   2940   3270   3500  3660   3730   3620   3700   3630   3700   3700   3530   3470   3470   3470   3450   3710   3740   3820   3760   3800   3830   3840   3890   3980   3990   4100   4110   4130   4140   4160   4240   4230   4230   4240   4260   4440   3770   3760   3840   3740   2620   2320   2150   2120   2100   1880   1820   1780   1780   1780   1800   1820   1840   1850   1890   1880   1860   1900   1890   1890   1950   2010   2060   2050   2110   2150   2230   2300   2380   2430   2460   2520   2580   2640   2690   2780   2830   2900   2680   2640   2390   2480   2460   2600   2900   2920   2840   2990   3150   3270   3390   3590   3130   2940   3050   2840   2810   2870   2960   3370   3510   3660   3750   3730   3830   3660   3730   3800   3890   4000   4100   4180   4310   4320   4420   4550   4680   4620   4680   4880   5060   5260   5370   5490   5610   5730     1

In [6]:
lex.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Columns: 302 entries, country to 2100
dtypes: float64(301), object(1)
memory usage: 460.2+ KB

In [7]:
lex.describe()

,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,...,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000
mean,31.503763,31.463441,31.480108,31.385484,31.460753,31.586559,31.644086,31.598387,31.385484,31.313441,...,83.361828,83.476344,83.600538,83.717742,83.838172,83.955376,84.076344,84.193548,84.312903,84.430645
std,3.809510,3.801217,3.932344,3.955872,3.928388,4.003874,4.102694,3.974506,4.080230,4.033412,...,5.803782,5.797854,5.788922,5.777904,5.770755,5.766333,5.756555,5.750616,5.743805,5.741341
min,23.400000,23.400000,23.400000,19.600000,23.400000,23.400000,23.400000,23.400000,12.500000,13.400000,...,66.400000,66.500000,66.700000,66.800000,66.900000,67.000000,67.100000,67.200000,67.300000,67.400000
25%,29.025000,28.925000,28.900000,28.900000,28.925000,29.025000,29.025000,29.025000,28.925000,28.825000,...,79.650000,79.750000,79.925000,80.025000,80.150000,80.325000,80.425000,80.525000,80.700000,80.800000
50%,31.750000,31.650000,31.550000,31.500000,31.550000,31.650000,31.750000,31.750000,31.550000,31.500000,...,84.000000,84.100000,84.250000,84.300000,84.500000,84.600000,84.700000,84.800000,84.900000,85.000000
75%,33.875000,33.900000,33.875000,33.675000,33.775000,33.875000,33.975000,33.975000,33.775000,33.675000,...,87.775000,87.875000,87.975000,88.075000,88.175000,88.300000,88.400000,88.500000,88.675000,88.775000
max,42.900000,40.300000,44.400000,44.800000,42.800000,44.300000,45.800000,43.600000,43.500000,41.700000,...,93.400000,93.500000,93.600000,93.700000,93.800000,94.000000,94.100000,94.200000,94.300000,94.400000

In [8]:
print(lex.value_counts())
print(lex.isnull())
print(lex.duplicated())

country              1800  1801  1802  1803  1804  1805  1806  1807  1808  1809  1810  1811  1812  1813  1814  1815  1816  1817  1818  1819  1820  1821  1822  1823  1824  1825  1826  1827  1828  1829  1830  1831  1832  1833  1834  1835  1836  1837  1838  1839  1840  1841  1842  1843  1844  1845  1846  1847  1848  1849  1850  1851  1852  1853  1854  1855  1856  1857  1858  1859  1860  1861  1862  1863  1864  1865  1866  1867  1868  1869  1870  1871  1872  1873  1874  1875  1876  1877  1878  1879  1880  1881  1882  1883  1884  1885  1886  1887  1888  1889  1890  1891  1892  1893  1894  1895  1896  1897  1898  1899  1900  1901  1902  1903  1904  1905  1906  1907  1908  1909  1910  1911  1912  1913  1914  1915  1916  1917  1918   1919  1920  1921  1922  1923  1924  1925  1926  1927  1928  1929  1930  1931  1932  1933  1934  1935  1936  1937  1938  1939  1940  1941  1942  1943  1944  1945  1946  1947  1948  1949  1950  1951  1952  1953  1954  1955  1956  1957  1958  1959  1960  1961  1962  1963  1964  1965  1966  1967  1968  1969  1970  1971  1972  1973  1974  1975  1976  1977  1978  1979  1980  1981  1982  1983  1984  1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019  2020  2021  2022  2023  2024  2025  2026  2027  2028  2029  2030  2031  2032  2033  2034  2035  2036  2037  2038  2039  2040  2041  2042  2043  2044  2045  2046  2047  2048  2049  2050  2051  2052  2053  2054  2055  2056  2057  2058  2059  2060  2061  2062  2063  2064  2065  2066  2067  2068  2069  2070  2071  2072  2073  2074  2075  2076  2077  2078  2079  2080  2081  2082  2083  2084  2085  2086  2087  2088  2089  2090  2091  2092  2093  2094  2095  2096  2097  2098  2099  2100
Afghanistan          28.2  28.2  28.2  28.2  28.2  28.2  28.1  28.1  28.1  28.1  28.1  28.1  28.1  28.1  28.1  28.1  28.1  28.0  28.0  28.0  28.0  28.0  28.0  28.0  28.0  27.9  27.9  27.9  27.9  27.9  27.9  27.9  27.9  27.9  27.9  27.9  27.8  27.8  27.8  27.8  27.8  27.8  27.8  27.8  27.8  27.8  27.7  27.7  27.7  27.7  27.7  27.7  27.7  27.7  27.7  27.6  27.6  27.6  27.6  27.6  27.6  27.6  27.6  27.6  27.6  27.5  27.5  27.5  27.5  27.5  27.5  27.7  27.9  28.1  28.3  28.5  28.7  28.9  29.1  29.3  29.4  29.6  29.8  30.0  30.2  30.4  30.6  30.8  31.0  31.2  31.4  31.6  31.8  32.0  32.2  32.4  32.5  32.7  32.9  33.1  33.3  33.5  33.7  33.9  34.1  34.3  34.5  34.7  34.9  35.0  35.2  35.4  35.6  35.8  36.0  36.2  36.4  36.6  9.59   36.9  37.1  37.3  37.5  37.7  37.9  38.1  38.3  38.4  38.6  38.8  39.0  39.2  39.4  39.6  39.8  39.9  40.1  40.3  40.5  40.7  40.9  41.0  41.2  41.4  41.6  41.8  42.0  42.2  42.4  42.5  42.7  42.9  43.1  43.5  43.3  43.9  44.1  44.3  44.5  44.7  45.0  45.3  45.5  45.7  45.9  46.1  46.3  46.5  46.7  46.9  47.1  47.3  47.3  47.3  47.4  47.5  47.7  47.9  46.4  44.7  43.7  44.3  44.1  42.3  39.9  42.0  43.3  45.9  48.5  52.7  53.8  53.8  54.2  54.4  53.9  54.3  54.7  54.5  53.3  54.7  54.7  54.8  55.5  56.5  57.1  57.6  58.0  58.5  59.2  59.9  60.5  61.0  61.4  61.9  61.9  61.9  62.0  62.9  62.7  63.3  63.4  64.0  64.3  64.6  64.9  65.2  65.4  65.7  66.0  66.2  66.4  66.6  66.9  67.1  67.3  67.5  67.7  67.9  68.0  68.2  68.4  68.6  68.8  68.9  69.1  69.2  69.4  69.5  69.7  69.8  70.0  70.2  70.3  70.4  70.6  70.7  70.9  71.0  71.1  71.3  71.4  71.5  71.7  71.8  72.0  72.1  72.2  72.3  72.5  72.6  72.7  72.9  73.0  73.1  73.3  73.4  73.5  73.7  73.8  74.0  74.1  74.2  74.3  74.5  74.6  74.8  74.9  75.0  75.2  75.3  75.4  75.5  75.7  75.8  76.0  76.1  76.2  76.4  76.5  76.6  76.8    1
Albania              35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.3  35.3  35.3  35.3  35.3  35.3  35.2  35.2  35.2  35.2  35.2  35.2  35.1  35.1  35.1  35.1  35.1  35.1  35.0  35.0  35.0  35.0  35.0  35.0  35.0  34.9  34.9  34.9  34.9  34.9  34.9  34.8  34.8  34.8  34.8  34.8  34.8  34.7  34.7  34.7  34.7  34.7  34.7  34.6  19.00  34.6  34.6  34.6  34.6  34.5  34.5  34.5  34.5  34.5  34.5  34.5  35.3  36.1  37.0  37.9  38.7  39.6  40.4  41.3  42.1  41.6  40.7  40.1  38.7  35.8  32.9  45.4  48.3  49.7  50.5  51.4  52.2  53.6  54.5  55.4  56.1  56.3  58.0  59.3  61.0  61.7  62.5  63.3  63.3  63.8  64.4  64.8  65.5  66.1  66.5  67.1  67.8  68.3  68.8  69.3  69.8  70.2  70.7  71.1  71.7  71.3  71.3  71.3  71.4  71.2  71.4  71.9  72.3  72.2  72.4  72.5  72.8  72.6  73.2  73.8  74.6  74.6  74.5  72.9  74.8  75.1  75.4  76.0  75.9  75.6  75.8  76.2  76.9  77.5  77.6  78.0  78.1  78.1  78.2  78.3  78.2  78.1  78.2  78.3  78.4  78.5  77.9  78.7  78.8  79.0  79.1  79.2  79.4  79.5  79.7  79.8  80.0  80.2  80.3  80.5  80.7  80.8  80.9  81.1  81.2  81.3  81.5  81.6  81.8  81.9  82.0  82.2  82.3  82.4  82.6  82.7  82.8  83.0  83.1  83.3  83.4  83.5  83.7  83.8  83.9  84.0  84.1  84.3  84.4  84.5  84.6  84.7  84.8  84.9  85.0  85.2  85.3  85.4  85.5  85.6  85.7  85.8  85.9  86.0  86.1  86.2  86.3  86.4  86.5  86.6  86.7  86.8  86.9  87.0  87.1  87.2  87.3  87.4  87.5  87.6  87.7  87.8  87.9  88.0  88.2  88.3  88.4    1
Algeria              28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  20.0  15.0  22.0  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  28.8  21.0  11.0  15.0  22.0  28.9  29.1  29.2  29.3  29.4  29.5  29.6  29.7  29.8  29.9  30.1  30.2  30.3  30.4  30.5  30.6  30.7  30.8  30.9  31.1  31.2  31.3  31.4  31.5  31.6  31.7  31.8  31.9  32.1  32.2  32.4  32.5  33.7  27.3  30.3  31.9  31.9  31.9  33.7  35.5  35.4  37.0  34.6  34.1  33.6  33.3  33.4  26.10  33.6  32.8  32.9  32.7  35.7  37.4  38.4  37.7  32.3  36.5  36.8  38.4  36.1  37.7  39.2  38.6  40.8  42.3  40.2  39.5  42.3  42.9  40.9  40.2  34.9  41.3  38.7  41.4  45.4  49.2  52.1  55.1  55.6  56.0  56.4  52.4  53.1  53.5  53.0  52.8  52.6  52.4  51.5  51.5  55.8  56.7  56.8  56.2  56.1  56.1  56.1  56.2  56.2  56.3  56.5  56.7  56.9  57.1  57.8  58.2  58.8  58.7  59.9  60.8  62.3  63.3  64.7  65.5  66.0  66.6  67.1  67.5  67.9  68.3  68.6  68.7  69.0  69.6  69.7  70.2  70.7  71.0  71.3  71.8  72.0  72.6  72.9  73.3  73.6  73.9  74.2  74.5  74.7  74.9  75.1  75.3  75.4  75.7  75.9  76.0  76.2  76.2  76.6  76.7  76.9  77.1  77.3  77.4  77.6  77.8  77.9  78.1  78.3  78.4  78.6  78.8  78.9  79.1  79.2  79.4  79.5  79.7  79.9  80.0  80.2  80.3  80.5  80.6  80.8  80.9  81.1  81.2  81.4  81.5  81.7  81.8  81.9  82.1  82.2  82.3  82.5  82.6  82.7  82.9  83.0  83.1  83.3  83.4  83.5  83.6  83.7  83.8  84.0  84.1  84.2  84.3  84.4  84.5  84.6  84.7  84.8  85.0  85.0  85.2  85.3  85.3  85.5  85.6  85.7  85.8  85.9  86.0  86.1  86.2  86.3  86.4  86.5  86.6  86.7  86.8  86.9  87.0    1
Angola               27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.2  27.4  27.6  27.7  27.9  28.1  28.3  28.5  28.7  28.9  29.1  29.3  29.4  29.6  29.8  30.0  30.2  30.4  30.6  30.8  30.9  31.1  31.3  31.5  31.7  31.9  32.1  32.3  32.5  32.6  32.8  33.0  33.2  33.4  33.6  33.8  34.0  34.2  34.4  34.5  34.7  34.9  35.1  35.3  35.5  35.7  35.9  13.90  36.2  36.4  36.6  36.8  37.0  37.2  37.4  37.6  37.8  37.9  38.1  38.3  38.5  38.7  38.9  39.1  39.3  39.5  39.6  39.8  40.0  40.2  40.7  41.3  41.8  42.3  42.9  43.4  43.9  44.5  45.0  45.6  45.6  45.6  45.6  45.6  45.5  45.7  45.8  45.9  46.1  46.3  44.8  45.0  45.2  45.4  45.6  45.8  46.0  46.2  46.4  46.6  46.8  47.0  47.2  47.4  47.5  47.5  47.7  47.8  48.0  48.1  48.2  48.2  48.2  48.4  48.6  48.6  48.6  48.6  49.4  49.7  50.3  50.3  49.0  50.3  51.2  51.7  51.6  50.6  51.9  52.8  53.4  54.5  55.1  55.5  56.4  57.0  58.0  58.8  59.5  60.2  60.8  61.4  62.1  63.0  63.5  63.9  64.2  64.6  65.1  65.2  65.8  66.1  66.4  66.8  67.1  67.4  67.7  68.0  68.3  68.6  68.9  69.2  69.4  69.7  70.0  70.2  70.5  70.7  70.9  71.1  71.4  71.6  71.8  72.0  72.2  72.4  72.5  72.7  72.9  73.1  73.3  73.4  73.6  73.8  73.9  74.1  74.2  74.4  74.5  74.7  74.8  75.0  75.1  75.3  75.4  75.5  75.7  75.8  76.0  76.1  76.2  76.4  76.5  76.6  76.8  76.9  77.0  77.2  77.3  77.4  77.5  77.7  77.8  77.9  78.0  78.2  78.3  78.4  78.6  78.7  78.8  79.0  79.1  79.2  79.3  79.5  79.6  79.7  79.9  80.0    1
Antigua and Barbuda  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.5  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.6  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  33.7  21.90  33.8  33.8  33.8  34.6  35.4  36.3  37.1  38.0  38.8  39.6  40.5  41.3  42.1  43.0  43.8  44.7  45.5  46.3  47.2  48.0  48.9  49.7  50.5  51.4  52.2  53.1  53.9  54.8  55.6  56.5  57.3  58.1  58.7  59.3  59.8  60.3  60.9  61.5  61.9  62.6  63.3  63.8  64.8  65.5  65.8  66.1  66.7  67.1  67.2  67.6  68.0  68.3  68.9  69.4  69.8  70.0  70.2  70.3  70.6  71.0  71.6  72.1  72.6  73.2  73.8  73.5  73.8  74.0  74.2  74.3  74.3  74.0  74.0  74.0  73.4  73.3  73.3  74.0  73.5  74.5  74.7  74.8  75.1  75.4  75.6  75.7  75.9  75.9  75.1  75.2  75.8  75.9  76.0  76.0  76.1  76.0  76.0  76.0  76.1  76.2  76.3  76.3  76.5  76.7  76.8  76.9  77.1  77.2  77.3  77.4  77.6  77.7  77.8  78.0  78.1  78.2  78.3  78.5  78.6  78.7  78.8  79.0  79.1  79.2  79.3  79.5  79.6  79.7  79.8  80.0  80.1  80.2  80.3  80.5  80.6  80.7  80.8  81.0  81.1  81.2  81.3  81.5  81.6  81.7  81.8  82.0  82.1  82.2  82.3  82.5  82.6  82.7  82.8  82.9  83.0  83.2  83.3  83.4  83.5  83.6  83.7  83.8  84.0  84.1  84.2  84.3  84.4  84.5  84.6  84.7  84.8  84.9  85.0  85.1  85.2  85.3  85.4  85.5  85.6  85.7  85.8  85.9    1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ..
Venezuela            32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.3  32.3  32.3  32.4  32.4  32.4  32.5  32.5  32.5  32.6  32.6  32.6  32.7  32.7  32.8  32.8  32.8  32.9  32.9  32.9  33.0  33.0  33.0  33.1  33.1  33.1  33.2  33.2  33.2  33.3  33.3  33.3  33.4  33.4  33.5  33.5  33.5  33.5  33.6  33.6  33.7  33.7  33.7  33.8  33.8  33.8  30.60  33.9  33.9  34.0  34.0  34.0  34.1  34.1  34.1  34.4  34.6  34.8  35.0  35.2  35.4  35.6  35.9  36.1  36.3  37.6  39.0  40.3  41.6  43.0  44.7  46.4  48.2  49.9  51.7  53.4  55.2  56.9  58.7  59.0  59.5  61.3  61.0  61.2  61.6  61.4  62.5  63.9  65.2  65.8  66.1  65.7  65.5  66.0  66.3  66.5  66.5  66.0  66.5  66.6  66.4  66.3  67.3  67.6  67.8  68.7  69.4  69.7  69.7  69.7  70.3  71.1  71.3  71.6  72.2  72.1  72.5  72.4  72.4  72.9  72.9  72.8  72.3  72.6  73.3  74.1  74.0  70.3  74.2  74.1  74.0  73.5  74.6  75.0  74.8  74.6  74.4  74.6  75.3  75.4  75.2  75.5  75.6  75.7  75.6  75.5  75.4  75.0  75.1  75.1  75.3  75.5  75.7  76.0  76.2  76.5  76.7  77.0  77.1  77.3  77.4  77.6  77.7  77.9  78.0  78.2  78.3  78.5  78.6  78.8  78.9  79.1  79.2  79.4  79.5  79.7  79.8  80.0  80.1  80.3  80.4  80.6  80.7  80.9  81.0  81.2  81.3  81.5  81.6  81.8  81.9  82.1  82.2  82.4  82.5  82.7  82.8  83.0  83.1  83.3  83.4  83.6  83.7  83.9  84.0  84.2  84.3  84.5  84.6  84.8  84.9  85.1  85.2  85.3  85.5  85.6  85.8  85.9  86.0  86.2  86.3  86.4  86.5  86.7  86.8  86.9  87.0  87.2  87.3    1
Vietnam              32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.0  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  32.1  20.60  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.2  32.4  32.5  32.7  32.9  33.0  33.2  34.6  35.9  37.3  36.3  35.4  34.8  33.2  27.2  17.1  36.3  42.3  47.4  50.4  52.3  52.6  53.0  53.3  53.8  56.4  56.8  57.2  57.6  58.0  58.4  58.7  58.4  58.0  58.6  57.4  57.7  57.9  53.9  56.0  56.0  56.6  52.8  56.1  55.8  62.3  64.9  65.3  65.7  65.9  66.3  66.6  66.9  67.1  67.5  67.8  68.1  68.4  68.6  68.9  69.2  69.5  69.8  70.2  70.5  70.8  71.1  71.3  71.7  72.0  72.2  72.4  72.5  72.6  72.7  72.8  72.9  72.9  73.0  73.1  73.2  73.3  73.5  73.6  73.7  73.9  74.0  74.2  74.3  74.5  74.5  74.7  74.8  74.9  75.0  75.1  75.3  75.4  75.6  75.8  75.9  76.1  76.3  76.4  76.5  76.7  76.8  77.0  77.1  77.2  77.4  77.5  77.7  77.8  78.0  78.1  78.2  78.4  78.5  78.7  78.8  79.0  79.1  79.3  79.4  79.5  79.7  79.8  80.0  80.1  80.3  80.4  80.5  80.7  80.8  81.0  81.1  81.2  81.3  81.5  81.6  81.7  81.9  82.0  82.1  82.2  82.3  82.5  82.6  82.7  82.8  82.9  83.0  83.2  83.3  83.4  83.5  83.6  83.7  83.8  83.9  84.0  84.2  84.3  84.4  84.5  84.6  84.7  84.8  84.9  85.0    1
Yemen                23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.4  23.5  23.6  23.7  23.8  23.9  24.0  24.1  24.2  24.3  24.4  24.6  24.7  24.8  24.9  25.0  25.1  25.2  25.3  25.4  25.5  25.6  25.7  25.8  25.9  26.0  26.1  26.2  26.4  26.5  26.6  26.7  26.8  26.9  27.0  27.1  27.2  27.3  27.4  27.5  27.6  27.7  27.8  27.9  28.0  28.1  28.3  28.4  23.60  28.6  28.7  28.8  28.9  29.0  29.1  29.2  29.3  29.4  29.5  29.6  29.7  29.8  29.9  30.1  30.2  30.3  30.4  30.5  30.6  30.7  30.8  30.9  31.0  31.1  31.2  31.3  31.4  31.5  31.6  31.8  31.9  32.3  32.6  33.0  33.2  33.4  33.8  34.4  35.0  35.7  36.5  37.1  36.3  36.9  37.6  38.2  38.8  39.4  40.2  41.0  41.9  44.3  45.4  46.6  47.6  48.7  49.8  50.9  51.8  52.6  53.3  54.0  54.3  55.5  56.1  56.7  55.2  57.7  58.2  58.6  59.1  59.5  59.9  60.3  60.5  61.1  61.5  62.0  62.5  63.0  63.5  64.0  64.5  64.9  65.3  65.8  66.2  66.5  66.9  67.2  67.6  67.8  67.9  68.4  68.5  68.2  67.5  67.3  66.1  67.7  67.8  67.9  68.0  68.1  68.3  68.4  68.6  68.8  69.0  69.2  69.4  69.7  69.9  70.1  70.2  70.4  70.5  70.6  70.8  70.9  71.0  71.1  71.3  71.4  71.5  71.6  71.7  71.8  72.0  72.1  72.2  72.3  72.4  72.5  72.7  72.8  72.9  73.0  73.1  73.2  73.3  73.4  73.5  73.7  73.8  73.9  74.0  74.1  74.2  74.3  74.4  74.5  74.7  74.8  74.9  75.0  75.1  75.2  75.3  75.5  75.6  75.7  75.8  75.9  76.0  76.2  76.3  76.4  76.5  76.7  76.8  76.9  77.0  77.1  77.3  77.4  77.5  77.6  77.8  77.9  78.0    1

In [9]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Columns: 302 entries, country to 2100
dtypes: object(302)
memory usage: 460.2+ KB

In [10]:
pop.describe()

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
count,195,195,195,195,195,195,195,195,195,195,...,195,195,195,195,195,195,195,195,195,195
unique,195,162,181,184,183,177,183,178,179,178,...,189,194,185,189,189,184,186,186,181,188
top,Afghanistan,2.5M,2M,1.01M,2.01M,2.02M,2.02M,2.03M,2.03M,2.04M,...,108M,108M,109M,109M,6.61M,1.68M,110M,17M,13.2M,5.02M
freq,1,6,4,3,3,4,4,3,3,5,...,2,2,2,2,3,3,2,3,3,2

In [11]:
print(pop.value_counts())
print(pop.isnull())
print(pop.duplicated())

country      1800   1801   1802   1803   1804   1805   1806   1807   1808   1809   1810   1811   1812   1813   1814   1815   1816   1817   1818   1819   1820   1821   1822   1823   1824   1825   1826   1827   1828   1829   1830   1831   1832   1833   1834   1835   1836   1837   1838   1839   1840   1841   1842   1843   1844   1845   1846   1847   1848   1849   1850   1851   1852   1853   1854   1855   1856   1857   1858   1859   1860   1861   1862   1863   1864   1865   1866   1867   1868   1869   1870   1871   1872   1873   1874   1875   1876   1877   1878   1879   1880   1881   1882   1883   1884   1885   1886   1887   1888   1889   1890   1891   1892   1893   1894   1895   1896   1897   1898   1899   1900   1901   1902   1903   1904   1905   1906   1907   1908   1909   1910   1911   1912   1913   1914   1915   1916   1917   1918   1919   1920   1921   1922   1923   1924   1925   1926   1927   1928   1929   1930   1931   1932   1933   1934   1935   1936   1937   1938   1939   1940   1941   1942   1943   1944   1945   1946   1947   1948   1949   1950   1951   1952   1953   1954   1955   1956   1957   1958   1959   1960   1961   1962   1963   1964   1965   1966   1967   1968   1969   1970   1971   1972   1973   1974   1975   1976   1977   1978   1979   1980   1981   1982   1983   1984   1985   1986   1987   1988   1989   1990   1991   1992   1993   1994   1995   1996   1997   1998   1999   2000   2001   2002   2003   2004   2005   2006   2007   2008   2009   2010   2011   2012   2013   2014   2015   2016   2017   2018   2019   2020   2021   2022   2023   2024   2025   2026   2027   2028   2029   2030   2031   2032   2033   2034   2035   2036   2037   2038   2039   2040   2041   2042   2043   2044   2045   2046   2047   2048   2049   2050   2051   2052   2053   2054   2055   2056   2057   2058   2059   2060   2061   2062   2063   2064   2065   2066   2067   2068   2069   2070   2071   2072   2073   2074   2075   2076   2077   2078   2079   2080   2081   2082   2083   2084   2085   2086   2087   2088   2089   2090   2091   2092   2093   2094   2095   2096   2097   2098   2099   2100
Afghanistan  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.28M  3.29M  3.3M   3.31M  3.32M  3.34M  3.35M  3.37M  3.38M  3.4M   3.41M  3.43M  3.45M  3.46M  3.48M  3.49M  3.51M  3.52M  3.54M  3.55M  3.57M  3.59M  3.6M   3.62M  3.63M  3.65M  3.67M  3.68M  3.7M   3.72M  3.73M  3.75M  3.77M  3.78M  3.8M   3.82M  3.84M  3.85M  3.87M  3.89M  3.9M   3.92M  3.94M  3.96M  3.98M  3.99M  4.01M  4.03M  4.05M  4.06M  4.08M  4.1M   4.12M  4.14M  4.16M  4.17M  4.19M  4.21M  4.23M  4.25M  4.27M  4.29M  4.31M  4.33M  4.35M  4.36M  4.38M  4.4M   4.42M  4.44M  4.46M  4.48M  4.5M   4.52M  4.54M  4.56M  4.58M  4.6M   4.62M  4.64M  4.67M  4.71M  4.75M  4.8M   4.86M  4.92M  4.98M  5.04M  5.11M  5.17M  5.3M   5.5M   5.79M  6.16M  6.62M  7.12M  7.65M  8.23M  8.85M  9.53M  9.98M  10.2M  10.2M  9.89M  9.37M  8.88M  8.42M  7.97M  7.56M  7.16M  6.85M  6.63M  6.48M  6.41M  6.41M  6.41M  6.41M  6.41M  6.41M  6.41M  6.43M  6.47M  6.53M  6.61M  6.71M  6.81M  6.92M  7.02M  7.13M  7.24M  7.36M  7.48M  7.57M  7.67M  7.76M  7.86M  7.97M  8.09M  8.21M  8.33M  8.47M  8.62M  8.79M  8.97M  9.16M  9.36M  9.57M  9.78M  10M    10.2M  10.5M  10.8M  11M    11.3M  11.6M  11.9M  12.2M  12.4M  12.7M  12.9M  13M    12.5M  11.2M  10.1M  9.95M  10.2M  10.5M  10.4M  10.3M  10.4M  10.7M  10.7M  10.7M  12.1M  14M    15.5M  16.4M  17.1M  17.8M  18.5M  19.3M  19.5M  19.7M  21M    22.6M  23.6M  24.4M  25.4M  25.9M  26.4M  27.4M  28.2M  29.2M  30.5M  31.5M  32.7M  33.8M  34.6M  35.6M  36.7M  37.8M  39M    40.1M  41.1M  42.2M  43.4M  44.5M  45.7M  46.8M  48M    49.2M  50.3M  51.5M  52.7M  53.9M  55M    56.2M  57.4M  58.6M  59.8M  61M    62.2M  63.4M  64.6M  65.8M  67M    68.2M  69.4M  70.5M  71.7M  72.9M  74.1M  75.2M  76.4M  77.5M  78.7M  79.8M  80.9M  82M    83.1M  84.2M  85.2M  86.2M  87.3M  88.2M  89.2M  90.2M  91.1M  92.1M  93M    93.9M  94.7M  95.6M  96.4M  97.2M  98M    98.7M  99.5M  100M   101M   102M   102M   103M   104M   104M   105M   105M   106M   106M   107M   107M   108M   108M   108M   109M   109M   109M   110M   110M   110M   111M   111M     1
Albania      400k   402k   404k   405k   407k   409k   411k   413k   414k   416k   418k   420k   422k   424k   426k   427k   429k   431k   433k   435k   437k   439k   441k   443k   445k   447k   449k   451k   453k   455k   457k   459k   461k   463k   465k   467k   470k   472k   474k   476k   478k   480k   482k   485k   487k   489k   491k   493k   496k   498k   501k   505k   510k   515k   519k   524k   529k   535k   540k   545k   550k   555k   561k   566k   571k   577k   582k   588k   594k   599k   605k   611k   616k   622k   628k   634k   640k   646k   652k   659k   665k   671k   678k   684k   690k   697k   704k   710k   717k   724k   731k   738k   745k   753k   760k   768k   775k   783k   791k   798k   806k   814k   821k   828k   836k   844k   851k   859k   867k   874k   881k   888k   894k   900k   906k   912k   918k   924k   930k   936k   941k   947k   952k   957k   962k   967k   972k   977k   982k   988k   995k   1M     1.01M  1.02M  1.03M  1.04M  1.06M  1.07M  1.08M  1.09M  1.1M   1.11M  1.13M  1.14M  1.15M  1.17M  1.18M  1.2M   1.21M  1.23M  1.25M  1.29M  1.33M  1.37M  1.41M  1.45M  1.5M   1.55M  1.6M   1.66M  1.71M  1.77M  1.83M  1.89M  1.95M  2.01M  2.07M  2.13M  2.2M   2.26M  2.32M  2.39M  2.46M  2.52M  2.59M  2.65M  2.71M  2.77M  2.83M  2.89M  2.94M  2.99M  3.04M  3.09M  3.13M  3.17M  3.21M  3.24M  3.26M  3.28M  3.3M   3.3M   3.3M   3.3M   3.29M  3.28M  3.27M  3.25M  3.23M  3.21M  3.18M  3.15M  3.12M  3.09M  3.06M  3.03M  3M     2.98M  2.95M  2.93M  2.91M  2.9M   2.89M  2.89M  2.88M  2.88M  2.88M  2.88M  2.88M  2.87M  2.87M  2.85M  2.84M  2.83M  2.83M  2.82M  2.82M  2.81M  2.8M   2.8M   2.79M  2.78M  2.77M  2.76M  2.75M  2.74M  2.72M  2.71M  2.69M  2.68M  2.66M  2.64M  2.62M  2.61M  2.59M  2.57M  2.54M  2.52M  2.5M   2.48M  2.46M  2.43M  2.41M  2.39M  2.36M  2.34M  2.31M  2.29M  2.27M  2.24M  2.22M  2.19M  2.17M  2.14M  2.12M  2.1M   2.07M  2.05M  2.02M  1.99M  1.97M  1.94M  1.92M  1.89M  1.86M  1.83M  1.81M  1.78M  1.75M  1.72M  1.69M  1.66M  1.63M  1.6M   1.57M  1.54M  1.5M   1.47M  1.44M  1.41M  1.38M  1.35M  1.32M  1.29M  1.26M  1.23M  1.21M  1.18M  1.15M  1.12M  1.1M     1
Algeria      2.5M   2.51M  2.52M  2.53M  2.54M  2.55M  2.56M  2.56M  2.57M  2.58M  2.59M  2.6M   2.61M  2.62M  2.63M  2.64M  2.65M  2.66M  2.67M  2.68M  2.69M  2.69M  2.7M   2.7M   2.71M  2.71M  2.72M  2.72M  2.73M  2.73M  2.74M  2.74M  2.75M  2.75M  2.76M  2.76M  2.77M  2.77M  2.78M  2.78M  2.79M  2.79M  2.8M   2.8M   2.81M  2.81M  2.82M  2.82M  2.83M  2.84M  2.85M  2.87M  2.9M   2.93M  2.96M  2.99M  3.02M  3.05M  3.08M  3.11M  3.14M  3.17M  3.21M  3.24M  3.27M  3.31M  3.34M  3.37M  3.41M  3.44M  3.48M  3.51M  3.55M  3.59M  3.62M  3.66M  3.7M   3.74M  3.77M  3.81M  3.85M  3.89M  3.93M  3.97M  4.01M  4.05M  4.09M  4.14M  4.18M  4.22M  4.26M  4.31M  4.35M  4.39M  4.43M  4.48M  4.52M  4.57M  4.61M  4.66M  4.72M  4.79M  4.86M  4.94M  5.02M  5.1M   5.19M  5.27M  5.36M  5.43M  5.5M   5.55M  5.59M  5.62M  5.65M  5.68M  5.71M  5.74M  5.77M  5.8M   5.85M  5.9M   5.96M  6.02M  6.09M  6.16M  6.22M  6.29M  6.36M  6.44M  6.53M  6.63M  6.74M  6.86M  6.98M  7.1M   7.23M  7.35M  7.48M  7.61M  7.74M  7.86M  7.99M  8.11M  8.23M  8.35M  8.48M  8.6M   8.73M  8.87M  9.02M  9.27M  9.52M  9.77M  10M    10.2M  10.5M  10.7M  10.9M  11.2M  11.4M  11.6M  11.8M  12M    12.2M  12.4M  12.6M  12.9M  13.2M  13.5M  13.8M  14.1M  14.4M  14.8M  15.2M  15.7M  16.5M  17.1M  17.6M  18.2M  18.7M  19.4M  20M    20.7M  21.4M  22.1M  22.9M  23.6M  24.2M  24.9M  25.5M  26.1M  26.7M  27.4M  27.9M  28.5M  29M    29.5M  29.9M  30.3M  30.8M  31.2M  31.6M  32.1M  32.5M  33M    33.4M  34M    34.6M  35.2M  35.9M  36.5M  37.3M  38M    38.8M  39.5M  40.3M  41.1M  41.9M  42.7M  43.5M  44.2M  44.9M  45.6M  46.3M  46.9M  47.5M  48.1M  48.7M  49.3M  49.8M  50.3M  50.8M  51.3M  51.8M  52.4M  52.9M  53.4M  53.9M  54.4M  54.9M  55.4M  56M    56.5M  57M    57.5M  58.1M  58.6M  59.1M  59.5M  60M    60.4M  60.9M  61.3M  61.7M  62M    62.4M  62.7M  63M    63.3M  63.6M  63.8M  64M    64.2M  64.5M  64.6M  64.8M  65M    65.2M  65.3M  65.5M  65.7M  65.8M  66M    66.1M  66.2M  66.4M  66.5M  66.7M  66.8M  66.9M  67M    67.1M  67.2M  67.3M  67.4M  67.5M  67.6M  67.7M  67.7M  67.8M  67.8M  67.9M  67.9M  67.9M  67.9M  67.9M  67.9M  67.9M  67.8M  67.8M    1
Andorra      2650   2650   2650   2650   2650   2650   2650   2650   2650   2650   2650   2650   2650   2650   2650   2650   2650   2650   2650   2660   2670   2680   2690   2710   2730   2750   2770   2790   2810   2830   2850   2870   2890   2910   2930   2950   2970   2990   3010   3030   3060   3080   3100   3120   3140   3170   3190   3210   3230   3260   3280   3300   3320   3340   3360   3390   3410   3430   3450   3470   3500   3520   3540   3560   3590   3610   3630   3660   3680   3710   3730   3750   3780   3800   3830   3850   3880   3900   3930   3950   3980   4000   4030   4050   4080   4110   4130   4160   4190   4210   4240   4270   4300   4320   4350   4380   4410   4440   4460   4490   4520   4550   4580   4610   4640   4670   4700   4730   4760   4800   4860   4920   5000   5090   5180   5270   5360   5460   5560   5620   5640   5620   5560   5460   5360   5260   5170   5070   4980   4920   4890   4880   4900   4960   5010   5060   5120   5170   5230   5280   5340   5390   5450   5510   5570   5630   5690   5750   5810   5890   6010   5830   5450   5310   5570   6120   6710   7330   7990   8700   9440   10.2k  11k    11.8k  12.7k  13.6k  14.5k  15.7k  17.1k  18.4k  19.9k  21.3k  22.8k  24.4k  26k    27.6k  29.3k  30.9k  32.6k  34.1k  35.6k  37k    38.6k  40.4k  42.2k  43.8k  45.6k  47.6k  49.7k  51.6k  53.6k  55.4k  57.3k  59.2k  61k    62.9k  64.1k  64.7k  65.2k  65.7k  66.1k  67.8k  70.8k  73.9k  76.9k  79.8k  80.2k  78.2k  76.1k  73.9k  71.5k  70.6k  71k    71.4k  71.6k  71.7k  72.5k  73.8k  75k    76.3k  77.7k  79k    79.8k  80.1k  80.3k  80.6k  80.8k  81k    81.2k  81.4k  81.5k  81.7k  81.8k  81.9k  82k    82.1k  82.2k  82.2k  82.2k  82.2k  82.2k  82.2k  82.1k  82k    81.9k  81.7k  81.6k  81.3k  81.1k  80.8k  80.5k  80.2k  79.8k  79.4k  78.9k  78.5k  78k    77.5k  77k    76.5k  75.9k  75.4k  74.9k  74.3k  73.8k  73.2k  72.7k  72.2k  71.6k  71.1k  70.6k  70.1k  69.6k  69.1k  68.7k  68.2k  67.8k  67.4k  66.9k  66.5k  66.1k  65.8k  65.4k  65k    64.7k  64.3k  64k    63.7k  63.4k  63.1k  62.8k  62.5k  62.2k  61.9k  61.7k  61.4k  61.2k  60.9k  60.7k  60.5k  60.2k    1
Angola       1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.57M  1.58M  1.59M  1.61M  1.64M  1.66M  1.69M  1.71M  1.74M  1.76M  1.79M  1.81M  1.84M  1.87M  1.9M   1.92M  1.95M  1.98M  2.01M  2.04M  2.07M  2.1M   2.13M  2.16M  2.19M  2.23M  2.26M  2.29M  2.33M  2.36M  2.39M  2.42M  2.45M  2.47M  2.49M  2.51M  2.53M  2.55M  2.57M  2.59M  2.61M  2.63M  2.65M  2.68M  2.7M   2.72M  2.74M  2.76M  2.79M  2.81M  2.83M  2.85M  2.87M  2.89M  2.91M  2.93M  2.95M  2.96M  2.98M  3M     3.02M  3.04M  3.06M  3.08M  3.09M  3.11M  3.13M  3.15M  3.17M  3.19M  3.2M   3.21M  3.21M  3.2M   3.19M  3.18M  3.17M  3.16M  3.14M  3.13M  3.12M  3.1M   3.08M  3.06M  3.04M  3.02M  3M     2.98M  2.96M  2.94M  2.92M  2.91M  2.89M  2.88M  2.87M  2.87M  2.86M  2.85M  2.84M  2.83M  2.83M  2.84M  2.86M  2.89M  2.94M  2.98M  3.02M  3.07M  3.12M  3.16M  3.21M  3.26M  3.3M   3.35M  3.4M   3.44M  3.49M  3.54M  3.59M  3.64M  3.69M  3.75M  3.81M  3.88M  3.95M  4.02M  4.09M  4.17M  4.24M  4.32M  4.4M   4.48M  4.57M  4.66M  4.76M  4.85M  4.94M  5.02M  5.1M   5.19M  5.27M  5.36M  5.44M  5.52M  5.6M   5.67M  5.74M  5.79M  5.83M  5.87M  5.93M  6.03M  6.18M  6.36M  6.58M  6.8M   7.03M  7.27M  7.51M  7.77M  8.04M  8.33M  8.63M  8.95M  9.28M  9.62M  9.97M  10.3M  10.7M  11.1M  11.4M  11.8M  12.2M  12.6M  13M    13.5M  13.9M  14.4M  14.9M  15.4M  15.9M  16.4M  16.9M  17.5M  18.1M  18.8M  19.5M  20.2M  20.9M  21.7M  22.5M  23.4M  24.3M  25.2M  26.1M  27.1M  28.1M  29.2M  30.2M  31.3M  32.4M  33.4M  34.5M  35.6M  36.7M  37.8M  38.9M  40.1M  41.3M  42.5M  43.7M  44.9M  46.2M  47.4M  48.7M  50M    51.3M  52.7M  54M    55.4M  56.7M  58.1M  59.5M  60.9M  62.3M  63.7M  65.1M  66.6M  68M    69.4M  70.9M  72.3M  73.8M  75.2M  76.7M  78.1M  79.6M  81M    82.5M  83.9M  85.4M  86.8M  88.2M  89.6M  91M    92.4M  93.8M  95.2M  96.6M  97.9M  99.3M  101M   102M   103M   105M   106M   107M   108M   110M   111M   112M   113M   114M   116M   117M   118M   119M   120M   121M   122M   123M   124M   125M   126M   127M   128M   129M   130M   131M   131M   132M   133M     1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ..
Venezuela    1M     978k   957k   936k   916k   896k   876k   857k   838k   820k   808k   795k   785k   776k   767k   759k   751k   742k   734k   731k   732k   738k   749k   765k   782k   798k   815k   833k   851k   871k   893k   918k   946k   977k   1.01M  1.04M  1.07M  1.11M  1.15M  1.18M  1.2M   1.22M  1.24M  1.25M  1.26M  1.27M  1.28M  1.29M  1.3M   1.31M  1.33M  1.34M  1.36M  1.37M  1.39M  1.41M  1.43M  1.44M  1.46M  1.48M  1.5M   1.52M  1.54M  1.56M  1.57M  1.59M  1.61M  1.63M  1.65M  1.68M  1.7M   1.73M  1.76M  1.79M  1.82M  1.85M  1.89M  1.92M  1.96M  1.99M  2.02M  2.06M  2.09M  2.12M  2.15M  2.18M  2.21M  2.24M  2.27M  2.31M  2.34M  2.37M  2.41M  2.44M  2.48M  2.52M  2.55M  2.59M  2.63M  2.66M  2.7M   2.73M  2.77M  2.8M   2.83M  2.86M  2.89M  2.92M  2.96M  2.99M  3.01M  3.04M  3.07M  3.09M  3.11M  3.14M  3.16M  3.19M  3.21M  3.23M  3.26M  3.28M  3.31M  3.35M  3.38M  3.41M  3.45M  3.48M  3.51M  3.55M  3.59M  3.64M  3.68M  3.73M  3.79M  3.84M  3.89M  3.94M  4M     4.07M  4.15M  4.24M  4.35M  4.47M  4.6M   4.73M  4.87M  5M     5.15M  5.31M  5.49M  5.73M  5.98M  6.23M  6.49M  6.75M  7.02M  7.29M  7.58M  7.87M  8.16M  8.45M  8.75M  9.06M  9.37M  9.69M  10M    10.3M  10.7M  11M    11.4M  11.7M  12.1M  12.4M  12.8M  13.2M  13.6M  14M    14.4M  14.8M  15.2M  15.6M  16.1M  16.5M  17M    17.4M  17.9M  18.3M  18.8M  19.3M  19.8M  20.2M  20.7M  21.2M  21.6M  22.1M  22.6M  23M    23.5M  24M    24.4M  24.9M  25.3M  25.8M  26.2M  26.7M  27.1M  27.5M  27.9M  28.3M  28.7M  29.1M  29.5M  29.8M  30.2M  30.5M  30.7M  30.6M  29.8M  29M    28.5M  28.2M  28.3M  28.8M  29.4M  29.9M  30.4M  30.9M  31.3M  31.7M  32M    32.3M  32.6M  32.9M  33.2M  33.4M  33.6M  33.9M  34.1M  34.3M  34.5M  34.6M  34.8M  35M    35.1M  35.3M  35.4M  35.6M  35.7M  35.8M  35.9M  36M    36.2M  36.3M  36.3M  36.4M  36.5M  36.6M  36.7M  36.8M  36.8M  36.9M  37M    37M    37.1M  37.1M  37.2M  37.2M  37.3M  37.3M  37.3M  37.3M  37.4M  37.4M  37.4M  37.4M  37.4M  37.3M  37.3M  37.3M  37.3M  37.2M  37.2M  37.1M  37.1M  37M    37M    36.9M  36.8M  36.7M  36.6M  36.5M  36.4M  36.3M  36.2M  36M    35.9M  35.8M  35.6M  35.5M  35.4M    1
Vietnam      4M     4.1M   4.2M   4.31M  4.41M  4.53M  4.64M  4.75M  4.87M  4.99M  5.12M  5.25M  5.38M  5.52M  5.65M  5.79M  5.94M  6.09M  6.24M  6.36M  6.44M  6.5M   6.51M  6.49M  6.47M  6.46M  6.44M  6.42M  6.4M   6.38M  6.36M  6.34M  6.32M  6.31M  6.29M  6.27M  6.25M  6.23M  6.21M  6.2M   6.18M  6.16M  6.14M  6.12M  6.11M  6.09M  6.07M  6.05M  6.04M  6.06M  6.11M  6.21M  6.35M  6.53M  6.72M  6.91M  7.1M   7.31M  7.51M  7.73M  7.95M  8.17M  8.41M  8.64M  8.89M  9.14M  9.4M   9.67M  9.94M  10.2M  10.4M  10.5M  10.6M  10.6M  10.6M  10.7M  10.7M  10.7M  10.8M  10.8M  10.8M  10.8M  10.9M  10.9M  10.9M  11M    11M    11M    11.1M  11.1M  11.1M  11.2M  11.2M  11.2M  11.3M  11.3M  11.3M  11.4M  11.4M  11.5M  11.8M  12.2M  12.7M  13.4M  14.1M  14.9M  15.7M  16.5M  17.4M  18.1M  18.6M  18.9M  19.1M  19M    18.9M  18.8M  18.7M  18.6M  18.6M  18.5M  18.4M  18.3M  18.2M  18.1M  18.1M  18M    17.9M  17.8M  17.8M  17.7M  17.7M  17.8M  17.8M  18M    18.1M  18.2M  18.3M  18.5M  18.6M  18.8M  19.1M  19.5M  20M    20.6M  21.2M  21.8M  22.5M  23.1M  23.8M  24.5M  25.1M  25.6M  26.2M  26.8M  27.5M  28.3M  29M    29.9M  30.8M  31.8M  32.7M  33.6M  34.5M  35.5M  36.5M  37.5M  38.4M  39.3M  40.1M  41M    41.9M  42.9M  43.9M  44.9M  45.9M  47M    48.2M  49.4M  50.7M  51.8M  53M    54.3M  55.6M  57M    58.4M  59.8M  61.2M  62.6M  64M    65.5M  66.9M  68.4M  69.8M  71.2M  72.5M  73.8M  74.9M  76.1M  77.1M  78.1M  79M    79.8M  80.6M  81.5M  82.3M  83.1M  84M    84.8M  85.6M  86.5M  87.4M  88.3M  89.3M  90.3M  91.2M  92.2M  93.1M  94M    94.9M  95.8M  96.6M  97.5M  98.2M  98.9M  99.5M  100M   101M   101M   102M   102M   103M   103M   104M   104M   104M   105M   105M   105M   105M   106M   106M   106M   106M   106M   107M   107M   107M   107M   107M   107M   107M   107M   107M   107M   107M   107M   107M   107M   106M   106M   106M   106M   106M   105M   105M   105M   105M   104M   104M   104M   103M   103M   103M   102M   102M   101M   101M   101M   100M   99.8M  99.4M  99M    98.6M  98.2M  97.8M  97.4M  97M    96.6M  96.2M  95.7M  95.3M  94.9M  94.5M  94M    93.6M  93.2M  92.8M  92.3M  91.9M  91.5M  91M      1

## Task 4: Unpivot the Data

In [12]:
gdp_new = pd.melt(gdp, id_vars='country', var_name='year',value_name='gdp', ignore_index=True)

print(gdp_new)

                    country  year    gdp
0               Afghanistan  1800    583
1                    Angola  1800    452
2                   Albania  1800    569
3                   Andorra  1800   1660
4      United Arab Emirates  1800   1390
...                     ...   ...    ...
58690                 Samoa  2100    16k
58691                 Yemen  2100   5730
58692          South Africa  2100  42.7k
58693                Zambia  2100  12.8k
58694              Zimbabwe  2100   7380

[58695 rows x 3 columns]

## Task 5: Standardize Units k, M and B

In [13]:
gdp_new['gdp'] = gdp_new['gdp'].replace({'k': '*1e3', 'M': '*1e6', 'B': '*1e9', np.nan :'0'}, regex=True).map(pd.eval).astype(int)

print(gdp_new)

                    country  year    gdp
0               Afghanistan  1800    583
1                    Angola  1800    452
2                   Albania  1800    569
3                   Andorra  1800   1660
4      United Arab Emirates  1800   1390
...                     ...   ...    ...
58690                 Samoa  2100  16000
58691                 Yemen  2100   5730
58692          South Africa  2100  42700
58693                Zambia  2100  12800
58694              Zimbabwe  2100   7380

[58695 rows x 3 columns]

## Task 6: Correct Data Types of Columns

In [14]:
gdp_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58695 entries, 0 to 58694
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  58695 non-null  object
 1   year     58695 non-null  object
 2   gdp      58695 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.3+ MB

In [15]:
gdp_new['year'] = gdp_new['year'].astype(int)

## Task 7: Create a Data Cleaning Function

In [16]:
def cleaner(df,value_name,value_name_dtype):
    x = pd.melt(df, id_vars='country', var_name='year', value_name= value_name, ignore_index=True)
    x[value_name] = x[value_name].replace({'k': '*1e3', 'M': '*1e6', 'B': '*1e9', np.nan :'0'}, regex=True).map(pd.eval).astype(value_name_dtype)
    x['year'] = x['year'].astype(int)
    return x

In [17]:
pop_new = cleaner(pop, 'pop', 'int')

In [18]:
lex_new = cleaner(lex, 'lex', 'float')

## Task 8: Merge the Three Datasets

In [19]:
merge1 = gdp_new.merge(pop_new, how='left', left_on=['country', 'year'], right_on=['country','year'])

In [20]:
gapminder_df = merge1.merge(lex_new, how='left',left_on=['country', 'year'], right_on=['country','year'])

print(gapminder_df)

                    country  year    gdp       pop   lex
0               Afghanistan  1800    583   3280000  28.2
1                    Angola  1800    452   1570000  27.0
2                   Albania  1800    569    400000  35.4
3                   Andorra  1800   1660      2650   0.0
4      United Arab Emirates  1800   1390     40200  30.7
...                     ...   ...    ...       ...   ...
58690                 Samoa  2100  16000    441000  80.8
58691                 Yemen  2100   5730  74200000  78.0
58692          South Africa  2100  42700  74600000  77.7
58693                Zambia  2100  12800  63600000  77.1
58694              Zimbabwe  2100   7380  35600000  74.4

[58695 rows x 5 columns]

## Task 9: Drop Null Rows

In [21]:
gapminder_df.dropna(inplace=True)

In [22]:
gapminder_df.reset_index(drop=True, inplace=True)

In [23]:
gapminder_df['gdp'] = gapminder_df['gdp'].astype(int)
gapminder_df['pop'] = gapminder_df['pop'].astype(int)

print(gapminder_df)

                    country  year    gdp       pop   lex
0               Afghanistan  1800    583   3280000  28.2
1                    Angola  1800    452   1570000  27.0
2                   Albania  1800    569    400000  35.4
3                   Andorra  1800   1660      2650   0.0
4      United Arab Emirates  1800   1390     40200  30.7
...                     ...   ...    ...       ...   ...
56583                 Samoa  2100  16000    441000  80.8
56584                 Yemen  2100   5730  74200000  78.0
56585          South Africa  2100  42700  74600000  77.7
56586                Zambia  2100  12800  63600000  77.1
56587              Zimbabwe  2100   7380  35600000  74.4

[56588 rows x 5 columns]

## Task 10: Generate Continent Column

In [24]:
gapminder_df['country_code'] = gapminder_df['country'].apply(lambda x: pc.country_name_to_country_alpha2(x, cn_name_format="default"))

In [25]:
gapminder_df[gapminder_df['country_code']=='TL'] = gapminder_df[gapminder_df['country_code']=='TL'].assign(country_code='TP')

In [26]:
gapminder_df['continent_code'] = gapminder_df['country_code'].apply(lambda x: pc.country_alpha2_to_continent_code(x))

In [27]:
gapminder_df['continent'] = gapminder_df["continent_code"].apply(lambda x: pc.convert_continent_code_to_continent_name(x))

In [28]:
gapminder_df.drop(columns=['country_code','continent_code'], inplace=True)

print(gapminder_df)

                    country  year    gdp       pop   lex continent
0               Afghanistan  1800    583   3280000  28.2      Asia
1                    Angola  1800    452   1570000  27.0    Africa
2                   Albania  1800    569    400000  35.4    Europe
3                   Andorra  1800   1660      2650   0.0    Europe
4      United Arab Emirates  1800   1390     40200  30.7      Asia
...                     ...   ...    ...       ...   ...       ...
56583                 Samoa  2100  16000    441000  80.8   Oceania
56584                 Yemen  2100   5730  74200000  78.0      Asia
56585          South Africa  2100  42700  74600000  77.7    Africa
56586                Zambia  2100  12800  63600000  77.1    Africa
56587              Zimbabwe  2100   7380  35600000  74.4    Africa

[56588 rows x 6 columns]

## Task 11: Filter Data by Years

In [29]:
df = gapminder_df[(gapminder_df['year'] > 1899) & (gapminder_df['year'] < 2024)]
print(df)

                    country  year    gdp       pop   lex continent
18800           Afghanistan  1900    846   4710000  33.3      Asia
18801                Angola  1900    701   3100000  32.6    Africa
18802               Albania  1900    758    806000  34.9    Europe
18803               Andorra  1900   4430      4520   0.0    Europe
18804  United Arab Emirates  1900   2780     48900  35.4      Asia
...                     ...   ...    ...       ...   ...       ...
42107                 Samoa  2023   5400    226000  71.0   Oceania
42108                 Yemen  2023   1780  34400000  68.1      Asia
42109          South Africa  2023  13300  60400000  66.1    Africa
42110                Zambia  2023   3270  20600000  64.2    Africa
42111              Zimbabwe  2023   2150  16700000  61.9    Africa

[23312 rows x 6 columns]

## Task 12: Plot the Data

In [30]:
fig = px.scatter(df, x='gdp', y='lex', animation_frame='year', animation_group='country',
       size='pop', color='continent', hover_name='country', log_x = True, size_max=100,
      range_x=[500,200000], range_y=[0,90], labels=dict(gdp="GDP Per Capita ($)",
        lex="Life Expectancy (years)", continent="Continents"),
        title = 'GDP Per Capita, Life Expectancy & Population (1900-2023)')
fig.update_layout(title_x=0.5,
              xaxis=dict(showgrid=False, tickmode = 'array',
                tickvals = [500, 1000, 10000, 100000, 200000],
                ticktext = [500, 1000, '10K', '100K','200K']),
              yaxis=dict(showgrid=False))

fig.show()